version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    volumes:
      - ..:/workspace:cached
    network_mode: service:db
    command: sleep infinity
  
  db:
    image: mariadb:10.5
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=calanimagealpha
      - MARIADB_USER=calanimagealpha
      - MARIADB_PASSWORD=calanimagealpha
      - MARIADB_DATABASE=calmoe

volumes:
  mariadb-data: